from __future__ import annotations

import json
from pathlib import Path
from typing import List

import yaml

from .models import GeneratedArtifact
from .models import MedspaClientSpec
from .models import PlatformGenerationResult
from .optimizer import run_platform_optimization
from .parser import parse_client_spec


def _json(data: object) -> str:
    return json.dumps(data, indent=2, sort_keys=False)


def _yaml(data: object) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=False)


def _ontology_extension(spec: MedspaClientSpec, result: PlatformGenerationResult | None = None) -> str:
    optimization = result.optimization if result else run_platform_optimization(spec)
    payload = {
        "version": "0.1.0",
        "platform_layer": "EVE_L5_Medspa_IaC",
        "client": spec.to_dict(),
        "routing": optimization.triage.to_dict(),
        "entities": {
            "service_nodes": [
                {
                    "id": f"service:{spec.slug}:{service.name.lower().replace(' ', '_')}",
                    "name": service.name,
                    "category": service.category,
                    "avg_ticket": service.avg_ticket,
                    "compliance_tags": service.compliance_tags,
                }
                for service in spec.services
            ],
            "persona_nodes": [
                {
                    "id": f"persona:{spec.slug}:{persona.name.lower().replace(' ', '_')}",
                    "name": persona.name,
                    "channels": persona.channels,
                    "concerns": persona.concerns,
                }
                for persona in spec.personas
            ],
            "location_nodes": [
                {
                    "id": f"location:{spec.slug}:{location.city.lower()}",
                    "city": location.city,
                    "state": location.state,
                    "timezone": location.timezone,
                }
                for location in spec.locations
            ],
        },
    }
    return _json(payload)


def _shacl_shapes(spec: MedspaClientSpec) -> str:
    return "\n".join(
        [
            "@prefix sh: <http://www.w3.org/ns/shacl#> .",
            "@prefix eve: <https://eve.local/ontology/> .",
            "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
            "",
            f"eve:{spec.slug}_ServiceShape a sh:NodeShape ;",
            "  sh:targetClass eve:Service ;",
            "  sh:property [ sh:path eve:name ; sh:datatype xsd:string ; sh:minCount 1 ] ;",
            "  sh:property [ sh:path eve:avgTicket ; sh:datatype xsd:decimal ; sh:minCount 1 ] ;",
            "  sh:property [ sh:path eve:category ; sh:datatype xsd:string ; sh:minCount 1 ] .",
            "",
            f"eve:{spec.slug}_PersonaShape a sh:NodeShape ;",
            "  sh:targetClass eve:Persona ;",
            "  sh:property [ sh:path eve:name ; sh:datatype xsd:string ; sh:minCount 1 ] ;",
            "  sh:property [ sh:path eve:preferredChannel ; sh:minCount 1 ] .",
            "",
            f"eve:{spec.slug}_LocationShape a sh:NodeShape ;",
            "  sh:targetClass eve:Location ;",
            "  sh:property [ sh:path eve:city ; sh:datatype xsd:string ; sh:minCount 1 ] ;",
            "  sh:property [ sh:path eve:state ; sh:datatype xsd:string ; sh:minCount 1 ] ;",
            "  sh:property [ sh:path eve:timezone ; sh:datatype xsd:string ; sh:minCount 1 ] .",
            "",
            f"eve:{spec.slug}_KpiShape a sh:NodeShape ;",
            "  sh:targetClass eve:KpiTarget ;",
            "  sh:property [ sh:path eve:conversionRate ; sh:datatype xsd:decimal ; sh:minInclusive 0 ; sh:maxInclusive 1 ] ;",
            "  sh:property [ sh:path eve:retentionRate ; sh:datatype xsd:decimal ; sh:minInclusive 0 ; sh:maxInclusive 1 ] ;",
            "  sh:property [ sh:path eve:monthlyRevenue ; sh:datatype xsd:decimal ; sh:minInclusive 1 ] .",
            "",
        ]
    )


def _supabase_sql(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    schema_name = f"l5_{spec.slug}"
    services_insert = "\n".join(
        [
            "insert into "
            + schema_name
            + ".service_catalog (service_name, category, avg_ticket, duration_minutes, compliance_tags)"
            + f"\nvalues ('{service.name}', '{service.category}', {service.avg_ticket:.2f}, {service.duration_minutes}, '{json.dumps(service.compliance_tags)}');"
            for service in spec.services
        ]
    )
    return f"""-- Generated by EVE L5_Medspa_IaC prototype
create schema if not exists {schema_name};

create table if not exists {schema_name}.client_profile (
    client_id text primary key,
    medspa_name text not null,
    primary_city text not null,
    branding jsonb not null,
    governance jsonb not null,
    thermo_triage jsonb not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists {schema_name}.service_catalog (
    id bigserial primary key,
    service_name text not null,
    category text not null,
    avg_ticket numeric not null,
    duration_minutes integer not null,
    compliance_tags jsonb not null default '[]'::jsonb
);

create table if not exists {schema_name}.persona_matrix (
    id bigserial primary key,
    persona_name text not null,
    channels jsonb not null,
    concerns jsonb not null,
    urgency_bias numeric not null
);

create table if not exists {schema_name}.journey_forecast (
    forecast_key text primary key,
    forecast_value numeric not null,
    explanation text not null
);

insert into {schema_name}.client_profile (
    client_id,
    medspa_name,
    primary_city,
    branding,
    governance,
    thermo_triage
) values (
    '{spec.client_id}',
    '{spec.medspa_name}',
    '{spec.primary_location.city}',
    '{json.dumps(spec.branding.to_dict())}'::jsonb,
    '{json.dumps(spec.governance.to_dict())}'::jsonb,
    '{json.dumps(result.optimization.triage.to_dict())}'::jsonb
)
on conflict (client_id) do update set
    medspa_name = excluded.medspa_name,
    primary_city = excluded.primary_city,
    branding = excluded.branding,
    governance = excluded.governance,
    thermo_triage = excluded.thermo_triage;

{services_insert}
"""


def _voice_agent_yaml(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    payload = {
        "version": "13.3+L5",
        "source_of_truth": "platform/l5_medspa_iac",
        "agent_identity": {
            "name": "EVE",
            "role": f"{spec.medspa_name} autonomous patient advocate",
        },
        "core_directives": [
            "Thermo_Triage gate before every escalation.",
            "Use tier_1/tier_2 routing for low-entropy calls; use full_matrix_routing for high-entropy or compliance-sensitive tasks.",
            "Run the V13.3 Emotional Resilience Inverter before objection handling.",
            "Red-team guards must remain active for DNC, HIPAA-safe messaging, AI disclosure, and no-medical-advice boundaries.",
        ],
        "persona_alignment": [
            {
                "persona": persona.name,
                "channels": persona.channels,
                "hook": f"Lead with {', '.join(persona.concerns[:2]) or 'high-intent demand'} and route toward booked consults."
            }
            for persona in spec.personas
        ],
        "services": [service.to_dict() for service in spec.services],
        "guardrails": {
            "red_team_matrix": [
                "ivr_overlap",
                "voicemail_edge_case",
                "hostile_gatekeeper",
                "hipaa_boundary",
                "dnc_compliance",
                "variable_template_leak",
            ],
            "compliance_rules": spec.compliance_rules,
            "thermo_triage": result.optimization.triage.to_dict(),
        },
    }
    return _yaml(payload)


def _workflow_json(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    workflow = {
        "name": f"{spec.medspa_name} - L5 orchestration",
        "meta": {
            "client_id": spec.client_id,
            "generated_by": "scripts/generate_l5_medspa_platform.py",
            "thermo_triage": result.optimization.triage.to_dict(),
        },
        "nodes": [
            {"id": "telegram_ingress", "type": "webhook", "path": f"l5-{spec.slug}-telegram-ingress"},
            {"id": "spec_loader", "type": "code", "purpose": "Load declarative client spec + ontology deltas"},
            {"id": "thermo_triage", "type": "code", "purpose": "Apply tier_1/tier_2/full_matrix routing"},
            {"id": "voice_dispatch", "type": "retell", "purpose": "Launch service/persona tuned voice agent"},
            {"id": "digital_twin", "type": "code", "purpose": "Run journey simulation + KPI forecast"},
            {"id": "governance_emit", "type": "supabase", "purpose": "Emit immutable telemetry + review tasks"},
        ],
        "connections": [
            ["telegram_ingress", "spec_loader"],
            ["spec_loader", "thermo_triage"],
            ["thermo_triage", "voice_dispatch"],
            ["thermo_triage", "digital_twin"],
            ["voice_dispatch", "governance_emit"],
            ["digital_twin", "governance_emit"],
        ],
    }
    return _json(workflow)


def _telegram_orchestrator_yaml(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    payload = {
        "client_id": spec.client_id,
        "telegram": {
            "command_prefix": f"/{spec.slug}",
            "ingress_workflow": f"l5-{spec.slug}-telegram-ingress",
            "owner_review_loop": "elijah_evebot_daily",
        },
        "routing": {
            "thermo_triage_gate": result.optimization.triage.gate_status,
            "tier": result.optimization.triage.tier,
            "route": result.optimization.triage.route,
            "least_action_path": result.optimization.triage.least_action_path,
        },
    }
    return _yaml(payload)


def _simulator_json(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    payload = {
        "client_id": spec.client_id,
        "medspa_name": spec.medspa_name,
        "baseline_kpis": spec.kpis.to_dict(),
        "forecast": result.optimization.forecast,
        "bottlenecks": result.optimization.bottlenecks,
        "pareto_frontier": [item.to_dict() for item in result.optimization.pareto_frontier],
        "selected_interventions": [item.to_dict() for item in result.optimization.selected_interventions],
        "journey_graph": result.optimization.journey_graph,
        "information_geometry": result.optimization.skill_embedding_distances,
    }
    return _json(payload)


def _governance_json(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    payload = {
        "client_id": spec.client_id,
        "immutable_telemetry": spec.governance.immutable_telemetry,
        "elijah_evebot_review_loop": spec.governance.elijah_review_loop,
        "review_triggers": [
            "voice_prompt_revision",
            "workflow_contract_drift",
            "acceptance_gate_failure",
            "telemetry_chain_gap",
        ],
        "acceptance_suite": spec.governance.acceptance_suite,
        "triage_policy": result.optimization.triage.to_dict(),
    }
    return _json(payload)


def _docker_compose(spec: MedspaClientSpec) -> str:
    return f"""version: "3.9"
services:
  eve_platform_{spec.slug}:
    image: python:3.11-slim
    working_dir: /app
    command: python3 scripts/generate_l5_medspa_platform.py --spec-file /config/client_spec.json --output-dir /state/generated/{spec.slug}
    volumes:
      - ./:/app
    environment:
      OPENCLAW_STATE_DIR: /state
      EVE_PLATFORM_CLIENT_ID: {spec.client_id}
  n8n:
    image: n8nio/n8n:latest
    environment:
      N8N_HOST: localhost
      OPENCLAW_N8N_BINDING_MODE: env
  voice_agent:
    image: python:3.11-slim
    working_dir: /app/agents/voice-agent/service
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8787
"""


def _pm2_ecosystem(spec: MedspaClientSpec) -> str:
    return f"""module.exports = {{
  apps: [
    {{
      name: "eve-l5-{spec.slug}",
      cwd: "/workspace",
      script: "python3",
      args: "scripts/generate_l5_medspa_platform.py --spec-file platform/l5_medspa_iac/specs/{spec.slug}.json --output-dir ${{OPENCLAW_STATE_DIR}}/generated/{spec.slug}",
      autorestart: true,
      max_restarts: 5,
      env: {{
        OPENCLAW_STATE_DIR: process.env.OPENCLAW_STATE_DIR || `${{process.env.HOME}}/.openclaw-eve`
      }}
    }}
  ]
}};
"""


def _launchd_plist(spec: MedspaClientSpec) -> str:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>ai.openclaw.eve.l5.{spec.slug}</string>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/bin/python3</string>
      <string>/workspace/scripts/generate_l5_medspa_platform.py</string>
      <string>--spec-file</string>
      <string>/workspace/platform/l5_medspa_iac/specs/{spec.slug}.json</string>
      <string>--output-dir</string>
      <string>/tmp/eve-platform/{spec.slug}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/eve-platform/{spec.slug}.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/eve-platform/{spec.slug}.err.log</string>
  </dict>
</plist>
"""


def _cloud_readme(spec: MedspaClientSpec, result: PlatformGenerationResult) -> str:
    return f"""# {spec.medspa_name} cloud-ready bundle

- Route profile: `{result.optimization.triage.route}`
- Tier: `{result.optimization.triage.tier}`
- Selected interventions: {", ".join(item.name for item in result.optimization.selected_interventions)}
- Suggested deploy path: Docker for local control plane, PM2 for runtime, launchd for operator automation.
- Governance: immutable telemetry on, Elijah_EveBot loop on.
"""


def _build_artifacts(spec: MedspaClientSpec, result: PlatformGenerationResult) -> List[GeneratedArtifact]:
    base = f"generated/{spec.slug}"
    return [
        GeneratedArtifact(f"{base}/ontology_extension.json", _ontology_extension(spec, result), "ontology"),
        GeneratedArtifact(f"{base}/ontology_shapes.ttl", _shacl_shapes(spec), "shacl"),
        GeneratedArtifact(f"{base}/supabase_extension.sql", _supabase_sql(spec, result), "sql"),
        GeneratedArtifact(f"{base}/retell_voice_agent.yaml", _voice_agent_yaml(spec, result), "voice"),
        GeneratedArtifact(f"{base}/n8n_workflow.json", _workflow_json(spec, result), "workflow"),
        GeneratedArtifact(f"{base}/telegram_orchestrator.yaml", _telegram_orchestrator_yaml(spec, result), "orchestrator"),
        GeneratedArtifact(f"{base}/digital_twin_simulator.json", _simulator_json(spec, result), "simulator"),
        GeneratedArtifact(f"{base}/governance_manifest.json", _governance_json(spec, result), "governance"),
        GeneratedArtifact(f"{base}/docker-compose.yml", _docker_compose(spec), "iac"),
        GeneratedArtifact(f"{base}/ecosystem.config.cjs", _pm2_ecosystem(spec), "iac"),
        GeneratedArtifact(f"{base}/launchd.plist", _launchd_plist(spec), "iac"),
        GeneratedArtifact(f"{base}/CLOUD_READY.md", _cloud_readme(spec, result), "doc"),
    ]


def generate_platform_bundle(source: str | dict) -> PlatformGenerationResult:
    spec = parse_client_spec(source)
    optimization = run_platform_optimization(spec)
    placeholder = PlatformGenerationResult(spec=spec, optimization=optimization, artifacts=[])
    artifacts = _build_artifacts(spec, placeholder)
    return PlatformGenerationResult(spec=spec, optimization=optimization, artifacts=artifacts)


def write_generation_result(result: PlatformGenerationResult, output_dir: str | Path) -> List[Path]:
    target_root = Path(output_dir)
    written: List[Path] = []
    for artifact in result.artifacts:
        path = target_root / artifact.path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(artifact.content, encoding="utf-8")
        written.append(path)
    manifest_path = target_root / f"generated/{result.spec.slug}/manifest.json"
    manifest_path.write_text(_json(result.to_dict()), encoding="utf-8")
    written.append(manifest_path)
    return written
